---
abstract: 'Create multi-page ticket creation wizards for RT'
author:
  - 'Best Practical Solutions, LLC'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-FormTools
no_index:
  directory:
    - etc
    - html
    - inc
    - lib/RT/Interface
    - po
    - static
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-extension-formtools
version: '1.17'
x_module_install_rtx_version: '0.43'
x_requires_rt: 5.0.5
