--- 
abstract: RT Extension-FormTools Extension
distribution_type: module
generated_by: Module::Install version 0.67
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Extension-FormTools
no_index: 
  directory: 
    - etc
    - html
    - inc
    - t
version: undef
